# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefe', models.CharField(max_length=40)),
                ('ipMaquina', models.CharField(max_length=128)),
                ('dataHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_registro', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='tipo_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencia.TipoRegistro'),
        ),
    ]
