# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0002_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dataHora',
        ),
        migrations.AddField(
            model_name='horario',
            name='hora',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
