# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0003_auto_20171113_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horario',
            field=models.ManyToManyField(to='frequencia.Horario'),
        ),
    ]
