# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0004_auto_20171113_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='consistente',
            field=models.BooleanField(default=False, verbose_name='Está pontual?'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='inconsistente',
            field=models.BooleanField(default=False, verbose_name='Está atrasado?'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='justificativa',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='ipMaquina',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.CharField(max_length=40),
        ),
    ]
